
project_id = "yvpsrnjyldlyqomlonop"

[functions.fetch-company-data]
verify_jwt = false

[functions.fetch-financial-data]
verify_jwt = false

[functions.create-payment]
verify_jwt = false

[functions.check-subscription]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.create-payment-intent]
verify_jwt = true

[functions.create-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.setup-admin]
verify_jwt = true
