// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yvpsrnjyldlyqomlonop.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl2cHNybmp5bGRseXFvbWxvbm9wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNjM0MDksImV4cCI6MjA2NTczOTQwOX0.7ZS-k5208kt62atnewZIzAOZl8bOxtCZP3xRh_MjLag";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);